#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : liberasurecode
Version  : 1.0.7
Release  : 4
URL      : https://bitbucket.org/tsg-/liberasurecode/get/v1.0.7.tar.gz
Source0  : https://bitbucket.org/tsg-/liberasurecode/get/v1.0.7.tar.gz
Summary  : C library with pluggable erasure code backends
Group    : Development/Tools
License  : BSD-2-Clause
Requires: liberasurecode-lib
Patch1: 0001-Use-correct-soname.patch

%description
liberasurecode
==============
liberasurecode is an Erasure Code API library written in C with pluggable Erasure Code backends.

%package dev
Summary: dev components for the liberasurecode package.
Group: Development
Requires: liberasurecode-lib

%description dev
dev components for the liberasurecode package.


%package lib
Summary: lib components for the liberasurecode package.
Group: Libraries

%description lib
lib components for the liberasurecode package.


%prep
%setup -q -n tsg--liberasurecode-a380246762c1
%patch1 -p1

%build
%autogen --disable-static
make V=1  %{?_smp_mflags}

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/*.h
/usr/lib64/*.so

%files lib
%defattr(-,root,root,-)
/usr/lib64/*.so.*
